# Generated by Django 3.0.7 on 2020-06-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_name', models.CharField(max_length=100)),
                ('vocab_detail', models.CharField(max_length=200)),
            ],
        ),
    ]
