# Generated by Django 3.0.7 on 2020-06-11 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vocab',
            new_name='vocabs',
        ),
    ]
