# Generated by Django 3.0.7 on 2020-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200611_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vocabs',
            new_name='vocab',
        ),
    ]
