# Generated by Django 3.0.7 on 2020-06-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200611_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='vocab_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocab',
            name='vocab_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
